<?php
return [
    'app_name' => getenv('SECUREIT_APP_NAME') ?: 'SecureIT',
    'base_url' => rtrim(getenv('SECUREIT_BASE_URL') ?: 'https://secureit.ict365.ky', '/'),
    'tenants_file' => getenv('SECUREIT_TENANTS_FILE') ?: __DIR__ . '/../data/tenants.json',
    'reports_root' => getenv('SECUREIT_REPORTS_ROOT') ?: __DIR__ . '/../data/reports',
    'identity_seeds_file' => getenv('SECUREIT_IDENTITY_SEEDS_FILE') ?: (file_exists(__DIR__ . '/../.local/identity-seeds.json') ? __DIR__ . '/../.local/identity-seeds.json' : ''),
    'canonical_controls_file' => getenv('SECUREIT_CANONICAL_CONTROLS_FILE') ?: __DIR__ . '/../data/canonical-controls.json',
    'canonical_controls_example_file' => __DIR__ . '/../config/canonical-controls.example.json',
    'test_descriptions_dir' => getenv('SECUREIT_TEST_DESCRIPTIONS_DIR') ?: __DIR__ . '/../data/maester-test-descriptions',
    'entra_authority' => getenv('SECUREIT_ENTRA_AUTHORITY') ?: 'organizations',
    'entra_client_id' => getenv('SECUREIT_ENTRA_CLIENT_ID') ?: '',
    'entra_client_secret' => getenv('SECUREIT_ENTRA_CLIENT_SECRET') ?: '',
    'entra_redirect_uri' => getenv('SECUREIT_ENTRA_REDIRECT_URI') ?: '',
    'entra_post_logout_redirect_uri' => getenv('SECUREIT_ENTRA_POST_LOGOUT_REDIRECT_URI') ?: '',
    'entra_allowed_tenant_ids' => getenv('SECUREIT_ENTRA_ALLOWED_TENANT_IDS') ?: '',
    'entra_admin_email_domains' => getenv('SECUREIT_ENTRA_ADMIN_EMAIL_DOMAINS') ?: 'ict365.ky',
    'entra_admin_app_role' => getenv('SECUREIT_ENTRA_ADMIN_APP_ROLE') ?: 'SecureIT.Admin',
    'azure_tenant_id' => getenv('SECUREIT_AZURE_TENANT_ID') ?: '',
    'azure_client_id' => getenv('SECUREIT_AZURE_CLIENT_ID') ?: '',
    'azure_client_secret' => getenv('SECUREIT_AZURE_CLIENT_SECRET') ?: '',
    'key_vault_name' => getenv('SECUREIT_KEY_VAULT_NAME') ?: '',
    'key_vault_uri' => getenv('SECUREIT_KEY_VAULT_URI') ?: '',
];
