<?php
return [
    'app_name' => getenv('SECUREIT_APP_NAME') ?: 'SecureIT',
    'base_url' => rtrim(getenv('SECUREIT_BASE_URL') ?: 'https://secureit.ict365.ky', '/'),
    'tenants_file' => getenv('SECUREIT_TENANTS_FILE') ?: __DIR__ . '/../data/tenants.json',
    'reports_root' => getenv('SECUREIT_REPORTS_ROOT') ?: __DIR__ . '/../data/reports',
    'identity_seeds_file' => getenv('SECUREIT_IDENTITY_SEEDS_FILE') ?: (file_exists(__DIR__ . '/../.local/identity-seeds.json') ? __DIR__ . '/../.local/identity-seeds.json' : ''),
    'canonical_controls_file' => getenv('SECUREIT_CANONICAL_CONTROLS_FILE') ?: __DIR__ . '/../data/canonical-controls.json',
    'canonical_controls_example_file' => __DIR__ . '/../config/canonical-controls.example.json',
    'test_descriptions_dir' => getenv('SECUREIT_TEST_DESCRIPTIONS_DIR') ?: __DIR__ . '/../data/maester-test-descriptions',
    'entra_authority' => getenv('SECUREIT_ENTRA_AUTHORITY') ?: 'organizations',
    'entra_tenant_id' => getenv('SECUREIT_ENTRA_TENANT_ID') ?: '',
    'entra_client_id' => getenv('SECUREIT_ENTRA_CLIENT_ID') ?: '',
    'entra_client_secret' => getenv('SECUREIT_ENTRA_CLIENT_SECRET') ?: '',
    'entra_redirect_uri' => getenv('SECUREIT_ENTRA_REDIRECT_URI') ?: '',
    'entra_post_logout_redirect_uri' => getenv('SECUREIT_ENTRA_POST_LOGOUT_REDIRECT_URI') ?: '',
    'entra_allowed_tenant_ids' => getenv('SECUREIT_ENTRA_ALLOWED_TENANT_IDS') ?: '',
    'entra_admin_email_domains' => getenv('SECUREIT_ENTRA_ADMIN_EMAIL_DOMAINS') ?: 'ict365.ky',
    'entra_admin_app_role' => getenv('SECUREIT_ENTRA_ADMIN_APP_ROLE') ?: 'SecureIT.Admin',
    'key_vault_tenant_id' => getenv('SECUREIT_KEY_VAULT_TENANT_ID') ?: '',
    'key_vault_client_id' => getenv('SECUREIT_KEY_VAULT_CLIENT_ID') ?: '',
    'key_vault_client_secret' => getenv('SECUREIT_KEY_VAULT_CLIENT_SECRET') ?: '',
    'key_vault_name' => getenv('SECUREIT_KEY_VAULT_NAME') ?: '',
    'key_vault_uri' => getenv('SECUREIT_KEY_VAULT_URI') ?: '',
    'workflow_sync_token' => getenv('SECUREIT_WORKFLOW_SYNC_TOKEN') ?: '',
    'github_repository' => getenv('SECUREIT_GITHUB_REPOSITORY') ?: 'matt-edu365/secureit',
    'github_workflow_file' => getenv('SECUREIT_GITHUB_WORKFLOW_FILE') ?: 'secureit-production.yml',
    'github_workflow_ref' => getenv('SECUREIT_GITHUB_WORKFLOW_REF') ?: 'main',
    'github_token' => getenv('SECUREIT_GITHUB_TOKEN') ?: '',
];
