<?php
return [
    'EIDSCA.GENERATED' => [
        'inspect' => 'the Entra security baseline settings that apply across identity, access, audit, and tenant configuration',
        'pass' => 'the baseline review completes without finding settings outside the expected security position',
        'fail' => 'one or more baseline settings are missing, weakened, or configured in a way that needs review',
        'why' => 'baseline drift is an early warning that tenant-wide security controls are no longer aligned with the agreed standard',
    ],
    'MTMDEANTIVIRUSPOLICY' => [
        'inspect' => 'Microsoft Defender antivirus policy configuration for managed endpoints',
        'pass' => 'Defender antivirus is configured and managed through policy',
        'fail' => 'antivirus policy is missing, incomplete, or not applied as expected',
        'why' => 'unmanaged antivirus settings leave endpoints more exposed to malware and make protection inconsistent across the organisation',
    ],
    'MTMDIHEALTHISSUES' => [
        'inspect' => 'Defender for Identity health signals and service issues',
        'pass' => 'no unresolved Defender identity health problems are reported',
        'fail' => 'health issues are present or sensors are not reporting correctly',
        'why' => 'identity threat detection depends on healthy sensors and service connectivity',
    ],
    'APPMANAGEMENTPOLICIES' => [
        'inspect' => 'application management policies that control app registration and credential behaviour',
        'pass' => 'application management policies are present and enforce the expected restrictions',
        'fail' => 'policies are missing or allow app credentials and registrations to be managed too loosely',
        'why' => 'weak app management controls can allow unmanaged applications or secrets to gain long-lived access to tenant data',
    ],
    'APPREGISTRATIONS' => [
        'inspect' => 'Entra app registrations, including ownership and registration governance',
        'pass' => 'app registrations are governed by approved ownership and registration controls',
        'fail' => 'apps are unmanaged, ownerless, over-permissioned, or can be created outside the approved process',
        'why' => 'compromised or poorly governed apps can access tenant data without going through normal user sign-in controls',
    ],
    'AUTHENTICATIONMETHODBASELINE' => [
        'inspect' => 'authentication method policies for approved and blocked sign-in methods',
        'pass' => 'only approved authentication methods are enabled and weaker methods are restricted',
        'fail' => 'legacy or weak authentication methods remain available to users',
        'why' => 'attackers often target weak authentication methods to bypass stronger sign-in protection',
    ],
    'CONDITIONALACCESSBASELINE' => [
        'inspect' => 'Conditional Access policies that enforce the tenant access baseline',
        'pass' => 'the expected baseline policies are enabled, targeted correctly, and not left in report-only mode',
        'fail' => 'required policies are missing, disabled, scoped too narrowly, or only reporting',
        'why' => 'Conditional Access is the main control point for enforcing secure access to Microsoft 365 services',
    ],
    'CONDITIONALACCESSWHATIF' => [
        'inspect' => 'Conditional Access policy outcomes using representative access scenarios',
        'pass' => 'the simulated scenarios receive the expected grant, block, or MFA decisions',
        'fail' => 'the policy simulation allows access that should be blocked or does not require expected controls',
        'why' => 'policy simulation helps find gaps before a real risky sign-in reaches business data',
    ],
    'ENTRARECOMMENDATIONS' => [
        'inspect' => 'active Microsoft Entra recommendations for identity and tenant configuration',
        'pass' => 'there are no unresolved recommendations that affect the expected security posture',
        'fail' => 'recommended security improvements remain open',
        'why' => 'unresolved recommendations often identify known configuration weaknesses or missed hardening opportunities',
    ],
    'GROUPS' => [
        'inspect' => 'Microsoft 365 group settings, ownership, and creation controls',
        'pass' => 'group creation and ownership are controlled and groups remain accountable',
        'fail' => 'groups can be created too freely, lack owners, or have governance issues',
        'why' => 'groups control access to Teams, SharePoint, mailboxes, and other shared business data',
    ],
    'MTAPPREGISTRATIONOWNERSWITHOUTMFA' => [
        'inspect' => 'owners of app registrations and whether their accounts are protected by MFA',
        'pass' => 'app registration owners have MFA protection enabled',
        'fail' => 'one or more app owners can administer applications without MFA protection',
        'why' => 'an attacker who compromises an app owner can change app permissions or credentials and gain persistent access',
    ],
    'MTENTITLEMENTMANAGEMENTDELETEDGROUPS' => [
        'inspect' => 'entitlement management access packages for references to deleted groups',
        'pass' => 'access packages do not rely on deleted groups',
        'fail' => 'deleted groups are still referenced by entitlement management configuration',
        'why' => 'stale group references can break access reviews and make access assignments unreliable',
    ],
    'MTENTITLEMENTMANAGEMENTINACTIVEPOLICIES' => [
        'inspect' => 'entitlement management policies that are inactive or no longer used',
        'pass' => 'access package policies are active, intentional, and still relevant',
        'fail' => 'inactive policies remain configured where they can confuse or weaken access governance',
        'why' => 'unused policies make it harder to prove that access is being granted through the correct approval path',
    ],
    'MTENTITLEMENTMANAGEMENTORPHANEDRESOURCES' => [
        'inspect' => 'entitlement management resources that no longer have a valid owner or backing resource',
        'pass' => 'resources in access packages are valid and owned',
        'fail' => 'orphaned resources are still available in entitlement management',
        'why' => 'orphaned resources can leave access unclear and make cleanup or audit work more difficult',
    ],
    'MTENTITLEMENTMANAGEMENTVALIDAPPROVERS' => [
        'inspect' => 'approver assignments in entitlement management policies',
        'pass' => 'approval steps point to valid users or groups',
        'fail' => 'approval is assigned to missing, invalid, or inappropriate approvers',
        'why' => 'access requests should be reviewed by accountable people before users receive sensitive permissions',
    ],
    'MTENTITLEMENTMANAGEMENTVALIDRESOURCEROLES' => [
        'inspect' => 'resource role assignments used by entitlement management access packages',
        'pass' => 'resource roles are valid and still map to the intended access',
        'fail' => 'invalid or stale resource roles are present',
        'why' => 'incorrect resource roles can grant the wrong access or prevent legitimate users from receiving the access they need',
    ],
    'MTENTRADEVICEREGISTRATIONPOLICY' => [
        'inspect' => 'Entra device registration settings for who can join or register devices',
        'pass' => 'device registration is limited to the approved users and policy conditions',
        'fail' => 'users can register or join devices outside the expected control boundary',
        'why' => 'uncontrolled device registration can introduce unmanaged devices into access decisions',
    ],
    'MTENTRAIDCONNECT' => [
        'inspect' => 'Entra ID Connect or cloud sync configuration for hybrid identity',
        'pass' => 'identity synchronization is healthy and configured as expected',
        'fail' => 'sync is unhealthy, stale, or configured in a way that needs attention',
        'why' => 'identity sync problems can break access, delay account changes, or leave disabled users active in cloud services',
    ],
    'MTHIGHRISKAPPPERMISSIONS' => [
        'inspect' => 'applications with high-risk permissions such as broad directory, mail, file, or tenant access',
        'pass' => 'high-risk permissions are absent or controlled through an approved consent process',
        'fail' => 'applications hold sensitive permissions without the expected review or approval',
        'why' => 'over-permissioned apps can expose large amounts of data if the app or its credentials are compromised',
    ],
    'MTONPREMISESSYNCHRONIZATION' => [
        'inspect' => 'on-premises synchronization status and related hybrid identity settings',
        'pass' => 'synchronization is current and operating as expected',
        'fail' => 'sync is failing, stale, or configured unexpectedly',
        'why' => 'synchronization issues can leave old access in place or prevent urgent identity changes reaching Microsoft 365',
    ],
    'MTSECURITYGROUPCREATIONRESTRICTED' => [
        'inspect' => 'who is allowed to create security groups',
        'pass' => 'security group creation is restricted to approved administrators or groups',
        'fail' => 'ordinary users can create security groups without approval',
        'why' => 'security groups are often used in access rules, so uncontrolled creation can weaken access governance',
    ],
    'MTTENANTCREATIONRESTRICTED' => [
        'inspect' => 'tenant creation settings that control whether users can create new Microsoft Entra tenants',
        'pass' => 'tenant creation is restricted to approved administrators',
        'fail' => 'users can create unmanaged tenants from corporate identities',
        'why' => 'unmanaged tenants can create shadow IT and move business activity outside normal security oversight',
    ],
    'PRIVILEGEDASSIGNMENTS' => [
        'inspect' => 'privileged role assignments and whether elevated access is permanent or unmanaged',
        'pass' => 'privileged roles are assigned only where needed and governed through the approved process',
        'fail' => 'privileged access is permanent, excessive, or not properly governed',
        'why' => 'privileged accounts can change tenant-wide security settings and are high-value targets',
    ],
    'MTINTUNECONNECTORHEALTH' => [
        'inspect' => 'Intune connector health and service connectivity',
        'pass' => 'required connectors are healthy and communicating',
        'fail' => 'a connector is unhealthy, disconnected, or not reporting',
        'why' => 'unhealthy connectors can stop device management, compliance, or app deployment from working reliably',
    ],
    'MTINTUNEPLATFORM' => [
        'inspect' => 'Intune platform and enrollment settings',
        'pass' => 'platform settings follow the expected device management baseline',
        'fail' => 'platform settings are missing, too permissive, or inconsistent with the baseline',
        'why' => 'device management settings determine whether corporate devices can be secured and monitored consistently',
    ],
    'XSPMCRITICALASSETMANAGEMENT' => [
        'inspect' => 'critical asset definitions in exposure management',
        'pass' => 'critical assets are identified and included in exposure review',
        'fail' => 'critical assets are missing or not classified correctly',
        'why' => 'security teams need to know which assets matter most so they can prioritise risk and remediation',
    ],
    'XSPMDEVICES' => [
        'inspect' => 'device exposure management coverage',
        'pass' => 'devices are included in exposure and risk review',
        'fail' => 'devices are missing from exposure management or have unresolved exposure findings',
        'why' => 'untracked device exposure makes it harder to find and fix attack paths into the organisation',
    ],
    'XSPMPRIVILEGEDIDENTITIES' => [
        'inspect' => 'privileged identities in exposure management',
        'pass' => 'privileged identities are identified and included in exposure review',
        'fail' => 'privileged identities are missing or have unresolved exposure findings',
        'why' => 'privileged identities create the highest-impact attack paths if they are exposed or misused',
    ],
    'MTCIS365PUBLICGROUP' => [
        'inspect' => 'Microsoft 365 groups that are public or broadly visible',
        'pass' => 'groups are private or intentionally public with appropriate governance',
        'fail' => 'public groups expose membership or content more broadly than intended',
        'why' => 'public groups can accidentally expose Teams, SharePoint, and shared mailbox content',
    ],
    'MTCISADMINCONSENTWORKFLOWENABLED' => [
        'inspect' => 'the admin consent workflow for application permission requests',
        'pass' => 'users must request approval before apps receive permissions that need administrator consent',
        'fail' => 'the approval workflow is disabled or app consent bypasses the expected review',
        'why' => 'consent review helps stop risky apps from gaining access to tenant data without oversight',
    ],
    'MTCISCLOUDADMIN' => [
        'inspect' => 'cloud administrator accounts and privileged access exposure',
        'pass' => 'cloud admin access is limited and protected according to policy',
        'fail' => 'too many accounts have cloud admin rights or those accounts lack expected protections',
        'why' => 'cloud admins can alter identity, security, and data access across the tenant',
    ],
    'MTCISCREATETENANTDISALLOWED' => [
        'inspect' => 'whether ordinary users can create new Microsoft Entra tenants',
        'pass' => 'tenant creation is disabled for non-administrators',
        'fail' => 'users can create additional tenants without approval',
        'why' => 'new unmanaged tenants can bypass company security, retention, and compliance controls',
    ],
    'MTCISCUSTOMERLOCKBOX' => [
        'inspect' => 'Customer Lockbox settings for Microsoft support access',
        'pass' => 'Customer Lockbox requires approval before Microsoft support can access customer content',
        'fail' => 'support access can occur without the expected customer approval workflow',
        'why' => 'approval control gives the customer visibility and consent over exceptional support access to data',
    ],
    'MTCISDEVICESWITHOUTCOMPLIANCEPOLICYMARKED' => [
        'inspect' => 'Intune compliance settings for devices without an assigned compliance policy',
        'pass' => 'devices without a compliance policy are marked non-compliant',
        'fail' => 'devices without a compliance policy can still be treated as compliant',
        'why' => 'unassessed devices should not be trusted for access to business services',
    ],
    'MTCISENSUREGUESTACCESSRESTRICTED' => [
        'inspect' => 'guest user access restrictions in Entra ID',
        'pass' => 'guest users have limited visibility into directory and tenant information',
        'fail' => 'guests can browse more tenant information than required',
        'why' => 'restricted guest visibility reduces information exposure to external users',
    ],
    'MTCISENSUREGUESTUSERDYNAMICGROUP' => [
        'inspect' => 'dynamic groups used to identify and manage guest users',
        'pass' => 'guest users are captured by an appropriate dynamic group or equivalent control',
        'fail' => 'guest users are not grouped consistently for policy, review, or reporting',
        'why' => 'consistent guest grouping makes it easier to apply controls and review external access',
    ],
    'MTCISENSUREUSERCONSENTTOAPPSDISALLOWED' => [
        'inspect' => 'user consent settings for third-party applications',
        'pass' => 'users cannot grant app permissions outside the approved consent process',
        'fail' => 'users can consent to applications without administrator review',
        'why' => 'unreviewed consent can allow phishing apps to gain access to mail, files, or profile data',
    ],
    'MTCISFORMSPHISHINGPROTECTIONENABLED' => [
        'inspect' => 'Microsoft Forms phishing protection settings',
        'pass' => 'Forms phishing protection is enabled',
        'fail' => 'Forms phishing protection is disabled or not configured',
        'why' => 'this reduces the chance that company forms are used to collect credentials or sensitive information',
    ],
    'MTCISGLOBALADMINCOUNT' => [
        'inspect' => 'the number of accounts assigned the Global Administrator role',
        'pass' => 'the number of global administrators is kept within the approved minimum range',
        'fail' => 'too many accounts have full tenant administration rights',
        'why' => 'every extra global administrator increases the chance and impact of privileged account compromise',
    ],
    'MTCISPASSWORDEXPIRY' => [
        'inspect' => 'tenant password expiry policy',
        'pass' => 'password expiry follows the approved policy for the tenant',
        'fail' => 'the password expiry setting does not match the expected configuration',
        'why' => 'clear password policy reduces avoidable account risk and keeps tenant configuration consistent',
    ],
    'MTCISSPOB2BINTEGRATION' => [
        'inspect' => 'SharePoint and OneDrive B2B integration settings',
        'pass' => 'external collaboration uses the approved B2B integration model',
        'fail' => 'B2B integration is disabled or configured in a way that weakens external sharing governance',
        'why' => 'B2B integration helps keep external users governed through identity controls and access reviews',
    ],
    'MTCISSPODEFAULTSHARINGLINK' => [
        'inspect' => 'the default sharing link type for SharePoint and OneDrive',
        'pass' => 'new sharing links default to a restricted audience',
        'fail' => 'new links default to broad or anonymous sharing',
        'why' => 'safe defaults reduce accidental data exposure when users share files',
    ],
    'MTCISSPODEFAULTSHARINGLINKPERMISSION' => [
        'inspect' => 'the default permission level for SharePoint and OneDrive sharing links',
        'pass' => 'new sharing links default to view-only or the approved least-privilege permission',
        'fail' => 'new links default to edit access or another overly permissive setting',
        'why' => 'least-privilege sharing helps prevent unintended changes or onward sharing of business files',
    ],
    'MTCISSPOGUESTACCESSEXPIRY' => [
        'inspect' => 'guest access expiry settings for SharePoint and OneDrive',
        'pass' => 'guest access expires after the approved period',
        'fail' => 'guest access does not expire or lasts longer than policy allows',
        'why' => 'expiry prevents old external access from remaining after a project or relationship has ended',
    ],
    'MTCISSPOGUESTCANNOTSHAREUNOWNEDITEM' => [
        'inspect' => 'whether guests can reshare SharePoint or OneDrive content they do not own',
        'pass' => 'guests cannot reshare content unless explicitly allowed',
        'fail' => 'guests can pass access to other people without owner approval',
        'why' => 'resharing by guests can spread sensitive files beyond the intended audience',
    ],
    'MTCISSPOPREVENTDOWNLOADMALICIOUSFILE' => [
        'inspect' => 'SharePoint and OneDrive protection against downloading files marked as malicious',
        'pass' => 'users are prevented from downloading files identified as malicious',
        'fail' => 'malicious files can still be downloaded',
        'why' => 'blocking malicious downloads reduces the chance of users spreading or executing harmful files',
    ],
    'MTCISTHIRDPARTYANDCUSTOMAPPS' => [
        'inspect' => 'third-party and custom app settings in integrated Microsoft 365 services',
        'pass' => 'third-party and custom apps are restricted or governed by approval',
        'fail' => 'apps can be added without the expected restrictions',
        'why' => 'uncontrolled apps can introduce data access and compliance risks outside normal change control',
    ],
    'MTCISTHIRDPARTYAPPLICATIONSDISALLOWED' => [
        'inspect' => 'tenant settings that allow users to add third-party applications',
        'pass' => 'third-party applications are blocked or require administrator approval',
        'fail' => 'users can add third-party applications without review',
        'why' => 'unreviewed applications may request access to mail, files, contacts, or directory information',
    ],
    'MTCISTHIRDPARTYSTORAGESERVICESRESTRICTED' => [
        'inspect' => 'third-party storage service integration settings',
        'pass' => 'external storage services are restricted according to policy',
        'fail' => 'users can connect unapproved third-party storage providers',
        'why' => 'unapproved storage paths can move business data outside retention, discovery, and protection controls',
    ],
    'MTCISUSEROWNEDAPPSRESTRICTED' => [
        'inspect' => 'whether users can create or own applications without approval',
        'pass' => 'user-owned apps are restricted or governed',
        'fail' => 'users can create and manage apps outside the approved process',
        'why' => 'unmanaged user-owned apps can accumulate permissions and credentials that outlive their business need',
    ],
    'MTCISWEAKAUTHENTICATIONMETHODSDISABLED' => [
        'inspect' => 'authentication methods considered weak or legacy',
        'pass' => 'weak methods are disabled or unavailable to users',
        'fail' => 'weak methods remain enabled',
        'why' => 'weak sign-in methods are easier to phish, intercept, or bypass than modern authentication',
    ],
    'MTCISAACTIVATIONNOTIFICATIONGLOBALADMIN' => [
        'inspect' => 'notifications for Global Administrator role activation',
        'pass' => 'the right administrators are notified when Global Administrator access is activated',
        'fail' => 'activation notifications are missing or sent to the wrong recipients',
        'why' => 'timely notification helps detect unexpected privileged access before it is misused',
    ],
    'MTCISAACTIVATIONNOTIFICATIONOTHER' => [
        'inspect' => 'notifications for activation of other privileged roles',
        'pass' => 'role activation notifications are enabled for the expected recipients',
        'fail' => 'activation notifications are disabled or incomplete',
        'why' => 'privileged role activation should be visible so suspicious elevation can be investigated quickly',
    ],
    'MTCISAAPPADMINCONSENT' => [
        'inspect' => 'administrator consent controls for applications',
        'pass' => 'administrator consent is required and handled through the approved review process',
        'fail' => 'applications can receive administrator consent without the expected controls',
        'why' => 'administrator consent can grant broad tenant access and should be reviewed before approval',
    ],
    'MTCISAAPPGROUPOWNERCONSENT' => [
        'inspect' => 'whether group owners can grant application consent for group data',
        'pass' => 'group owner consent is restricted or governed by approval',
        'fail' => 'group owners can grant app access outside the approved process',
        'why' => 'group data often includes files, conversations, and membership information that should not be exposed casually',
    ],
    'MTCISAAPPREGISTRATION' => [
        'inspect' => 'who can register applications in the tenant',
        'pass' => 'application registration is restricted to approved users or administrators',
        'fail' => 'users can register applications without approval',
        'why' => 'uncontrolled app registration can create unmanaged identities with access to business data',
    ],
    'MTCISAAPPUSERCONSENT' => [
        'inspect' => 'whether users can grant consent to applications',
        'pass' => 'user consent is blocked or limited to low-risk approved permissions',
        'fail' => 'users can grant app access without suitable review',
        'why' => 'malicious apps often rely on user consent to gain access without stealing a password',
    ],
    'MTCISAASSIGNMENTNOTIFICATION' => [
        'inspect' => 'notifications for privileged role assignment changes',
        'pass' => 'assignment notifications are sent to the expected recipients',
        'fail' => 'role assignment changes can happen without the right notification',
        'why' => 'new privileged assignments should be visible so unexpected access can be challenged',
    ],
    'MTCISAAUTHENTICATORCONTEXT' => [
        'inspect' => 'authentication context requirements for sensitive actions or resources',
        'pass' => 'sensitive access requires the expected additional authentication context',
        'fail' => 'sensitive access is allowed without the required authentication context',
        'why' => 'step-up authentication protects high-risk actions even when a normal sign-in has succeeded',
    ],
    'MTCISABLOCKHIGHRISKSIGNINS' => [
        'inspect' => 'Conditional Access protection for high-risk sign-ins',
        'pass' => 'high-risk sign-ins are blocked or challenged as policy requires',
        'fail' => 'high-risk sign-ins can continue without the expected control',
        'why' => 'risk-based blocking reduces the chance that stolen credentials lead to successful access',
    ],
    'MTCISABLOCKHIGHRISKUSERS' => [
        'inspect' => 'policy controls for users marked as high risk',
        'pass' => 'high-risk users are blocked, remediated, or forced through approved recovery',
        'fail' => 'high-risk users can continue accessing services without remediation',
        'why' => 'high-risk users may already be compromised and should not retain normal access',
    ],
    'MTCISABLOCKLEGACYAUTH' => [
        'inspect' => 'legacy authentication protocols across Microsoft 365 sign-ins',
        'pass' => 'legacy authentication is blocked',
        'fail' => 'legacy authentication remains available',
        'why' => 'legacy protocols often bypass MFA and are a common path for password-spray attacks',
    ],
    'MTCISACLOUDGLOBALADMIN' => [
        'inspect' => 'Global Administrator access for cloud-only administrator accounts',
        'pass' => 'cloud global administrator access is limited and protected',
        'fail' => 'cloud administrator access is excessive or insufficiently controlled',
        'why' => 'global administrators can change security settings, create access, and disable protections across the tenant',
    ],
    'MTCISACROSSTENANTINBOUNDDEFAULT' => [
        'inspect' => 'default inbound cross-tenant access settings',
        'pass' => 'inbound access from other tenants is restricted by default',
        'fail' => 'external tenants receive broader inbound access than policy allows',
        'why' => 'restricting inbound defaults reduces exposure from partner or external tenant compromise',
    ],
    'MTCISADIAGNOSTICSETTINGS' => [
        'inspect' => 'diagnostic and audit log export settings',
        'pass' => 'diagnostic logs are enabled and routed to the expected destination',
        'fail' => 'important logs are not captured or not exported correctly',
        'why' => 'security investigation depends on having reliable logs after an incident',
    ],
    'MTCISAGLOBALADMINCOUNT' => [
        'inspect' => 'the number of accounts with the Global Administrator role',
        'pass' => 'global administrator count stays within the approved range',
        'fail' => 'too many accounts have global administrator rights',
        'why' => 'reducing the number of global administrators limits the blast radius of account compromise',
    ],
    'MTCISAGLOBALADMINRATIO' => [
        'inspect' => 'the share of users who hold Global Administrator rights',
        'pass' => 'global administrators are a small, controlled subset of the tenant',
        'fail' => 'the tenant has an unusually high ratio of global administrators',
        'why' => 'privileged access should be exceptional, not common, to reduce avoidable security risk',
    ],
    'MTCISAGUESTINVITATION' => [
        'inspect' => 'who is allowed to invite guest users',
        'pass' => 'guest invitations are limited to approved users or administrators',
        'fail' => 'guest invitations are open more broadly than policy allows',
        'why' => 'guest invitations create external access and should be controlled before outsiders enter the tenant',
    ],
    'MTCISAGUESTUSERACCESS' => [
        'inspect' => 'guest user permissions and directory visibility',
        'pass' => 'guest users have restricted access and limited directory visibility',
        'fail' => 'guests can see or access more tenant information than required',
        'why' => 'least-privilege guest access reduces exposure when working with external users',
    ],
    'MTCISAMANAGEDDEVICE' => [
        'inspect' => 'managed device security and compliance expectations',
        'pass' => 'managed devices meet the expected security baseline',
        'fail' => 'managed devices are missing required protections or compliance state',
        'why' => 'device posture is part of deciding whether access to corporate data should be trusted',
    ],
    'MTCISAMANAGEDDEVICEREGISTRATION' => [
        'inspect' => 'device registration rules for managed devices',
        'pass' => 'device registration is restricted and aligned with management policy',
        'fail' => 'devices can register without the expected controls',
        'why' => 'controlled registration helps keep unmanaged or personal devices from being treated as trusted assets',
    ],
    'MTCISAMETHODSMIGRATION' => [
        'inspect' => 'migration status for authentication methods policy',
        'pass' => 'authentication methods are managed through the modern policy approach',
        'fail' => 'the tenant still relies on older or incomplete authentication method configuration',
        'why' => 'modern policy management makes sign-in controls easier to enforce and audit consistently',
    ],
    'MTCISAMFA' => [
        'inspect' => 'multi-factor authentication requirements for users and access scenarios',
        'pass' => 'MFA is required where policy expects it',
        'fail' => 'users or scenarios can access services without MFA',
        'why' => 'MFA is one of the most effective controls against stolen-password attacks',
    ],
    'MTCISANOTIFYHIGHRISKUSERS' => [
        'inspect' => 'notification settings for users flagged as high risk',
        'pass' => 'high-risk users receive the expected notification or remediation prompt',
        'fail' => 'high-risk users are not notified or guided through remediation',
        'why' => 'fast notification helps users and administrators respond before suspicious access causes damage',
    ],
    'MTCISAPASSWORDEXPIRATION' => [
        'inspect' => 'password expiration policy for cloud users',
        'pass' => 'password expiration matches the agreed tenant policy',
        'fail' => 'password expiration is configured contrary to the agreed policy',
        'why' => 'consistent password policy avoids confusion and supports the chosen identity security model',
    ],
    'MTCISAPERMANENTROLEASSIGNMENT' => [
        'inspect' => 'permanent privileged role assignments',
        'pass' => 'privileged roles are eligible or time-bound rather than permanently active where possible',
        'fail' => 'privileged roles are assigned permanently without the expected justification',
        'why' => 'standing privileged access gives attackers more opportunity if an account is compromised',
    ],
    'MTCISAPHISHRESISTANT' => [
        'inspect' => 'phishing-resistant authentication requirements for users who need stronger protection',
        'pass' => 'phishing-resistant methods are required for the intended users or scenarios',
        'fail' => 'users can rely on weaker MFA methods where phishing-resistant sign-in is expected',
        'why' => 'phishing-resistant MFA reduces the risk of token theft and adversary-in-the-middle attacks',
    ],
    'MTCISAPRIVILEGEDPHISHRESISTANT' => [
        'inspect' => 'phishing-resistant authentication for privileged users',
        'pass' => 'privileged users must use phishing-resistant sign-in methods',
        'fail' => 'privileged users can administer the tenant with weaker authentication methods',
        'why' => 'administrator compromise has tenant-wide impact, so privileged sign-in needs stronger protection',
    ],
    'MTCISAREQUIREACTIVATIONAPPROVAL' => [
        'inspect' => 'approval requirements for activating privileged roles',
        'pass' => 'role activation requires approval where policy expects it',
        'fail' => 'privileged roles can be activated without the required approval',
        'why' => 'approval creates a human checkpoint before high-impact access becomes active',
    ],
    'MTCISAUNMANAGEDROLEASSIGNMENTS' => [
        'inspect' => 'privileged role assignments that are not managed through the approved governance process',
        'pass' => 'privileged assignments are managed, reviewed, and accountable',
        'fail' => 'unmanaged privileged assignments are present',
        'why' => 'unmanaged privileged access is difficult to review and easy to forget after business need ends',
    ],
    'MTCISAWEAKFACTOR' => [
        'inspect' => 'weak authentication factors available to users',
        'pass' => 'weak factors are disabled or excluded from sensitive access',
        'fail' => 'users can authenticate with weak or easily phished factors',
        'why' => 'attackers target weak factors because they are easier to bypass than modern authentication',
    ],
    'MTCISASPOSHARING' => [
        'inspect' => 'SharePoint and OneDrive external sharing settings',
        'pass' => 'sharing is limited to the approved audience and sharing model',
        'fail' => 'sharing is broader than policy allows',
        'why' => 'external sharing controls help prevent sensitive files being exposed outside the organisation',
    ],
    'MTCISASPOSHARINGALLOWEDDOMAIN' => [
        'inspect' => 'allowed or blocked domains for SharePoint and OneDrive external sharing',
        'pass' => 'external sharing is limited to approved domains where required',
        'fail' => 'users can share with domains outside the approved list',
        'why' => 'domain restrictions reduce accidental sharing with untrusted organisations',
    ],
    'INSPECTAZPSASSIGNMENT' => [
        'inspect' => 'who is allowed to use Azure PowerShell and Microsoft Graph PowerShell',
        'pass' => 'access is limited to assigned users, groups, or roles',
        'fail' => 'the PowerShell apps can be used more broadly than policy allows',
        'why' => 'unrestricted PowerShell access can let ordinary or guest users enumerate and abuse tenant data',
    ],
    'INSPECTAZPSMODULES' => [
        'inspect' => 'the Azure and Microsoft Graph PowerShell service principals',
        'pass' => 'the expected service principals are present and configured as intended',
        'fail' => 'the expected service principal configuration is missing or not hardened correctly',
        'why' => 'these app registrations are the control point for limiting legacy PowerShell access to tenant data',
    ],
    'INSPECTDOMAINEXPIRATION' => [
        'inspect' => 'custom domain registrations still attached to the tenant',
        'pass' => 'all associated domains are still owned and valid',
        'fail' => 'an associated domain has expired or is otherwise at risk of takeover',
        'why' => 'an expired domain can let an attacker reclaim a trusted tenant namespace and misuse it',
    ],
    'INSPECTEXOFULLACCESS' => [
        'inspect' => 'Exchange mailboxes with FullAccess delegates',
        'pass' => 'mailbox delegate access is limited to approved users and groups',
        'fail' => 'one or more mailboxes have FullAccess delegates that should not be there',
        'why' => 'FullAccess lets another account read and act on mailbox content, so it needs close review',
    ],
    'INSPECTEXOHIDDENMAILBOXES' => [
        'inspect' => 'Exchange mailboxes hidden from the Global Address List',
        'pass' => 'mailboxes are hidden only when that choice is intentional and approved',
        'fail' => 'mailboxes are hidden without a clear business reason',
        'why' => 'hidden mailboxes can make persistence and exfiltration harder to spot',
    ],
    'INSPECTEXOSENDASPERMISSIONS' => [
        'inspect' => 'Exchange mailboxes with SendAs delegates',
        'pass' => 'SendAs delegation is restricted to approved accounts',
        'fail' => 'a mailbox can be impersonated through SendAs permissions that should not exist',
        'why' => 'SendAs can let a user send mail as another person or mailbox, which is a common abuse path',
    ],
    'INSPECTEXOSENDONBEHALFOF' => [
        'inspect' => 'Exchange mailboxes with SendOnBehalfOf delegates',
        'pass' => 'SendOnBehalfOf delegation is only granted where the business need is clear',
        'fail' => 'mailboxes can be used on behalf of other users without the expected approval',
        'why' => 'this permission can mislead recipients and expose mail flow to abuse',
    ],
    'INSPECTEMAILVERIFIEDUSERCREATION' => [
        'inspect' => 'users created through email-verified self-service sign-up',
        'pass' => 'self-service creation is restricted or only produces approved accounts',
        'fail' => 'the tenant is allowing email-verified user creation that is not being governed',
        'why' => 'uncontrolled self-service accounts can create unmanaged identities inside the tenant',
    ],
    'INSPECTLARGEATTACHMENTBLOCKINGRULE' => [
        'inspect' => 'transport rules that block overly large email attachments',
        'pass' => 'mail flow includes an attachment-size control where the business expects one',
        'fail' => 'large attachments can be delivered without the expected block or review',
        'why' => 'large attachments are often used for malware delivery or data exfiltration',
    ],
    'INSPECTLINKEDINCONNECTION' => [
        'inspect' => 'LinkedIn account-linking settings for tenant users',
        'pass' => 'users cannot link work accounts more broadly than policy allows',
        'fail' => 'users can share data with LinkedIn when the organisation does not want that exposure',
        'why' => 'linked accounts can expose profile, contact, and calendar data outside Microsoft 365',
    ],
    'INSPECTMAILBOXESWITHINTERNALFORWARDING' => [
        'inspect' => 'mailboxes with forwarding or inbox rules that send mail internally',
        'pass' => 'forwarding is only present where it is known and approved',
        'fail' => 'mailboxes can forward messages internally in ways that should be reviewed',
        'why' => 'forwarding rules are a common way to quietly move mail out of a compromised mailbox',
    ],
    'INSPECTMSOLPOWERSHELL' => [
        'inspect' => 'whether the legacy MSOnline PowerShell module is still available',
        'pass' => 'the tenant has moved away from legacy MSOL access',
        'fail' => 'MSOL PowerShell remains enabled even though it is deprecated',
        'why' => 'legacy PowerShell access expands the attack surface and supports older automation paths',
    ],
    'INSPECTOFFICEMESSAGEENCRYPTION' => [
        'inspect' => 'Office Message Encryption configuration for Exchange mail',
        'pass' => 'the tenant has message encryption configured where required',
        'fail' => 'messages can be sent without the expected encryption protection',
        'why' => 'encryption helps keep sensitive business mail from being readable if it is intercepted',
    ],
    'INSPECTOUTGOINGSHARINGMONITORED' => [
        'inspect' => 'monitoring of outgoing SharePoint sharing invitations',
        'pass' => 'external sharing invitations are being monitored as expected',
        'fail' => 'the tenant is not tracking outgoing sharing events where it should',
        'why' => 'without monitoring, risky sharing can continue unnoticed after data has left the tenant',
    ],
    'INSPECTPARTNERSUPPORT' => [
        'inspect' => 'hidden Partner Tier1 and Partner Tier2 support role assignments',
        'pass' => 'those privileged partner roles are empty or only contain approved members',
        'fail' => 'unwanted hidden partner support assignments exist in the tenant',
        'why' => 'these roles can grant very powerful administrative access and are easy to overlook',
    ],
    'INSPECTSHAREPOINTLEGACYAUTHENABLED' => [
        'inspect' => 'SharePoint legacy authentication settings',
        'pass' => 'legacy authentication is disabled or otherwise constrained as expected',
        'fail' => 'SharePoint still allows older authentication flows',
        'why' => 'legacy auth is easier to attack and often bypasses modern protections',
    ],
    'INSPECTSIMPHISH' => [
        'inspect' => 'mail flow rules that bypass protections for simulated phishing traffic',
        'pass' => 'phishing simulation bypass rules are absent or tightly controlled',
        'fail' => 'mail rules weaken filtering in ways that could be abused for real attacks',
        'why' => 'bypasses that help training tools can also help attackers hide malicious mail',
    ],
    'INSPECTEDISCOVERYADMINS' => [
        'inspect' => 'eDiscovery case administrator assignments',
        'pass' => 'only approved users hold eDiscovery administrator access',
        'fail' => 'too many users can search and export sensitive content through eDiscovery',
        'why' => 'eDiscovery access can expose mailbox and content data across the tenant',
    ],
];
